### ISSUE TITLE
hi, can it be used, I downloaded the exe file and double clicked it but no response

### ISSUE THREAD

**Issue by aqianga78** [drash99/FallGuysTracker#1]
hi, can it be used, I downloaded the exe file and double clicked it but no response

**Comment by drash99** [comment]
First, check %userprofile%\AppData\LocalLow\Mediatonic\FallGuys_client\Player.log exists. I didn't make exception for non-existing log file. If not, launch Fall Guys once. 
If window just launched and closed, download new binary(I've updated binary in 0.1.0). I've patched some bugs today.

**Comment by aqianga78** [comment]
Does it only support EPIC GAME?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seunghyun ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 晚上11:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [drash99/FallGuysTracker] hi, can it be used, I downloaded the exe file and double clicked it but no response (Issue #1)






首先，检查 %userprofile%\AppData\LocalLow\Mediatonic\FallGuys_client\Player.log 是否存在。我没有为不存在的日志文件例外。如果没有，请启动 Fall Guys 一次。
如果窗口刚刚启动并关闭，请下载新的二进制文件（我已在 0.1.0 中更新了二进制文件）。我今天修复了一些错误。

—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ***@***.***与&gt;

**Comment by drash99** [comment]
I believe not, as I am playing with steam version.

**Comment by aqianga78** [comment]
The log exists, and it flashes back after double-clicking,&nbsp;I want to reply to the video, but it doesn't allow




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seunghyun ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 晚上11:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [drash99/FallGuysTracker] hi, can it be used, I downloaded the exe file and double clicked it but no response (Issue #1)





 
我不相信，因为我正在玩蒸汽版本。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。消息 ID：<drash99/FallGuysTracker/issues/1/1292249970 @ github 。com&gt;

**Comment by drash99** [comment]
then can you send the log file to seunghyun@duck.com?

**Comment by aqianga78** [comment]
Has been sent




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seunghyun ***@***.***&gt;; 
发送时间: 2022年10月27日(星期四) 凌晨0:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [drash99/FallGuysTracker] hi, can it be used, I downloaded the exe file and double clicked it but no response (Issue #1)





 
***@***.***吗？
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ID: ***@***.***&gt;

**Comment by drash99** [comment]
I found out the log file of yours and mine had different format. I fixed it and uploaded new release. 
Thanks for your report.

**Comment by drash99** [comment]
Sorry I've forgot to remove debugging code. If you already downloaded, can you download again 0.1.2? I changed it.

**Comment by aqianga78** [comment]
ok, i fell asleep yesterday and now at work, i'll try it when i get home from get off work, thank you very much for your help, thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Seunghyun ***@***.***&gt;; 
发送时间: 2022年10月27日(星期四) 凌晨1:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [drash99/FallGuysTracker] hi, can it be used, I downloaded the exe file and double clicked it but no response (Issue #1)






抱歉，我忘了删除调试代码。如果你已经下载了，可以再下载0.1.2吗？我改变了它。

—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您编写了该主题。Message ***@***.***与&gt;
